"""Generate the Caddy per-instance route blocks from instances.json.

    python deploy/gen_routes.py            -> deploy/routes-lan.caddy   (this PC)
    python deploy/gen_routes.py --ec2      -> deploy/routes.caddy       (the box)

Why only the ROUTES are generated
---------------------------------
The Caddyfile is the single thing standing between the internet/LAN and an API that
places real orders. Regenerating it wholesale would put every security decision --
`require_and_verify`, `strict_sni_host insecure_off`, which certificate is used --
into a template that nobody reviews line by line, and a template bug there fails
OPEN.

So `Caddyfile.lan` stays hand-written and `import`s this file, which contains only
the boring part: one `handle_path` per instance. A bug here can misroute a request;
it cannot switch off client-certificate authentication.

If this file is missing, `caddy validate` fails and caddy_local.ps1 refuses to start
the proxy -- fail closed, same as every other gate in this deployment.

Two output names on purpose
---------------------------
`routes-lan.caddy` (LAN cert, this PC) and `routes.caddy` (EC2). Distinct filenames
so a LAN config can never be shipped to the box or vice versa -- the same reasoning
that keeps certs-lan/ separate from certs/.

WHY handle_path AND NOT handle: handle_path STRIPS the matched prefix, so uvicorn
receives `/api/state`. Plain `handle` would forward `/a1/api/state` and every request
would 404 against a server that is working perfectly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parent
sys.path.insert(0, str(APP))

import instances  # noqa: E402  (needs APP on sys.path first)

HEADER = """\
# GENERATED by deploy/gen_routes.py from instances.json -- DO NOT EDIT BY HAND.
# Regenerate:  python deploy/gen_routes.py{flag}
#
# One handle_path per account. `handle_path` (not `handle`) strips the prefix, so the
# backend sees /api/state and needs no root_path. These are evaluated in order and are
# mutually exclusive; the catch-all `handle` in the parent Caddyfile MUST stay last so
# the default instance keeps answering at /.
#
# A backend that is not running answers 502 through its prefix. That is intended: a
# visibly broken route beats a silently missing one.
"""

BLOCK = """
# {label}  ->  127.0.0.1:{port}
#
# The bare path needs its own handler. `handle_path /{name}/*` matches /{name}/... but NOT
# /{name}, so typing the URL without a trailing slash falls through to the catch-all and the
# DEFAULT server answers 404 -- which reads as "this account does not exist" when in fact the
# request never reached it. Redirect instead of matching /{name}* , because that would also
# swallow /{name}anything.
handle /{name} {{
\tredir /{name}/ 308
}}

handle_path /{name}/* {{
\treverse_proxy 127.0.0.1:{port} {{
\t\theader_up X-Client-Cert-CN {{http.request.tls.client.subject}}
\t\t# The /ws quote feed is a long-lived response; do not buffer it.
\t\tflush_interval -1
\t}}
}}
"""


def render(items: list[dict], ec2: bool) -> str:
    out = [HEADER.format(flag=" --ec2" if ec2 else "")]
    for inst in items:
        out.append(BLOCK.format(name=inst["name"], port=inst["port"],
                                label=inst["label"]))
    if not items:
        out.append("\n# (no instances configured -- only the catch-all applies)\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ec2", action="store_true",
                    help="write routes.caddy (the box) instead of routes-lan.caddy")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the file on disk differs from what we would write")
    args = ap.parse_args()

    target = HERE / ("routes.caddy" if args.ec2 else "routes-lan.caddy")
    # The box's instance list is deploy/instances.ec2.json, NOT the laptop's
    # XauOrderPad/instances.json. Reading the laptop's file for --ec2 would generate
    # routes pointing at ports the box does not run, and Caddy would serve them --
    # 502 at best, another account's server at worst.
    source = (HERE / "instances.ec2.json") if args.ec2 else None
    try:
        items = instances.load(source)
    except instances.ConfigError as exc:
        sys.exit(f"CONFIG ERROR\n{exc}")

    text = render(items, args.ec2)

    if args.check:
        current = target.read_text("utf-8") if target.exists() else ""
        if current != text:
            sys.exit(f"{target.name} is STALE relative to instances.json. "
                     f"Run: python deploy/gen_routes.py"
                     f"{' --ec2' if args.ec2 else ''}")
        print(f"{target.name} is up to date")
        return 0

    target.write_text(text, "utf-8")
    print(f"wrote {target} ({len(items)} instance route(s))")
    for inst in items:
        print(f"    /{inst['name']}/*  ->  127.0.0.1:{inst['port']}   {inst['label']}")
    print("    /*            ->  the catch-all in the parent Caddyfile (default instance)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
